package com.gaoya.mdm.webhook.cxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-02T09:54:56.982+08:00
 * Generated source version: 3.4.2
 *
 */
@WebService(targetNamespace = "http://webhook.mdm.gaoya.com/", name = "MdmDataModelWebhook")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MdmDataModelWebhook {

    @WebMethod
    @Action(input = "http://webhook.mdm.gaoya.com/MdmDataModelWebhook/hookRequest", output = "http://webhook.mdm.gaoya.com/MdmDataModelWebhook/hookResponse")
    @WebResult(name = "return", targetNamespace = "http://webhook.mdm.gaoya.com/", partName = "return")
    public java.lang.String hook(

        @WebParam(partName = "arg0", name = "arg0")
        java.lang.String arg0
    );
}
