package com.gaoya.mdm.webhook;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.2
 * 2021-03-02T09:52:50.338+08:00
 * Generated source version: 3.4.2
 *
 */
@WebServiceClient(name = "MdmDataModelWebhookService",
                  wsdlLocation = "http://0.0.0.0:12346/ws/webhook?wsdl",
                  targetNamespace = "http://webhook.mdm.gaoya.com/")
public class MdmDataModelWebhookService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webhook.mdm.gaoya.com/", "MdmDataModelWebhookService");
    public final static QName MdmDataModelWebhookPort = new QName("http://webhook.mdm.gaoya.com/", "MdmDataModelWebhookPort");
    static {
        URL url = null;
        try {
            url = new URL("http://0.0.0.0:12346/ws/webhook?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MdmDataModelWebhookService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://0.0.0.0:12346/ws/webhook?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MdmDataModelWebhookService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MdmDataModelWebhookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MdmDataModelWebhookService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public MdmDataModelWebhookService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MdmDataModelWebhookService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MdmDataModelWebhookService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns MdmDataModelWebhook
     */
    @WebEndpoint(name = "MdmDataModelWebhookPort")
    public MdmDataModelWebhook getMdmDataModelWebhookPort() {
        return super.getPort(MdmDataModelWebhookPort, MdmDataModelWebhook.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MdmDataModelWebhook
     */
    @WebEndpoint(name = "MdmDataModelWebhookPort")
    public MdmDataModelWebhook getMdmDataModelWebhookPort(WebServiceFeature... features) {
        return super.getPort(MdmDataModelWebhookPort, MdmDataModelWebhook.class, features);
    }

}
